version: '3.7'

services:
  mars-rover-kata:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: mars-rover-kata
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
